version: '3'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:3000
        volumes: 
            - .:/code
        ports: 
            - 3000:3000
        depends_on: 
            - db
    
    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    
volumes: 
    postgres_data: